### ISSUE TITLE
화살표 함수

### ISSUE THREAD

**Issue by sungbin5304** [gamepann/PANN-Utils#2]
=> 쓰는법 알려줘요!

**Comment by Lumia1108** [comment]
=>는 람다 연산자입니다.
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/%EC%95%A0%EB%A1%9C%EC%9A%B0_%ED%8E%91%EC%85%98
모질라 문서 첨부합니다.
그리고 이슈는 단순히 프로그래밍 모르는 것을 물어보는 것이 아니라 프로젝트에 이상한 점,궁금한 점 등을 물어보기 위한 용도입니다.
